[project]
name = "birthday-filter"
version = "0.1.0"
description = "Creates a copy of a birthday calendar filtered to only specific people"
authors = [
    {name = "Radian LLC", email = "contact+birthday-filter@radian.codes"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv>=1.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
